### ISSUE TITLE
Timer Pins routed to the Arduino Due Board

### ISSUE THREAD

**Issue by pklaus** [ivanseidel/DueTimer#11]
DueTimer's [Readme](https://github.com/ivanseidel/DueTimer#readme) states:

> Prefer to use Timer3, Timer4 and Timer5 since they have no connection to hardware pins. 

I don't quite get this. Which pins are you talking about? The timer (counter) input pins as I read Atmel's datasheet are mostly routed to headers on the Arduino Due board (with the exception of T6 and T7):

| Timer Pin Name | SAM3X Pin | Pin of Arduino Due Board |
| --- | --- | --- |
| TCLK0 | PB26 | Digital Pin 22 |
| TCLK1 | PA4 | Analog In 5 |
| TCLK2 | PA7 | Digital Pin 31 |
| TCLK3 | PA22 | Analog In 3 |
| TCLK4 | PA23 | Analog In 2 |
| TCLK5 | PB16 | DAC1 |
| TCLK6 | PC27 | n/a |
| TCLK7 | PC30 | LED "RX" |
| TCLK8 | PD9 | Digital Pin 30 |

My sources: Section _37.5.1 I/O Lines_ in the [Atmel SAM3X Datasheet](http://www.atmel.com/images/doc11057s.pdf) and [Arduino Due's SAM3X Pin Mapping](http://arduino.cc/en/Hacking/PinMappingSAM3X).

It would be great if this could be clarified or corrected. Thanks!

**Comment by sriranjanr** [comment]
Could you please tell me how to set the timer to receive an external clock input on TCLK0. I tried every where but could not get an answer.

**Comment by radosek21** [comment]
Hi sriranjanr,
I was also struggling with the same problem. I wanted to divide clock on the DAC1 pin by 100. Here is this solution
```
  // Setup the counter on DAC1 pin
  pmc_set_writeprotect(false);
  pmc_enable_periph_clk(TC5_IRQn); // Set interrupt handler to TCLK5
  TC_Configure(TC1, 2, TC_CMR_WAVE | TC_CMR_WAVSEL_UP_RC | TC_CMR_TCCLKS_XC2); // Set external clock input
  TC_SetRC(TC1, 2, 100); // Every 100th clock will be invoked interrupt 
  TC1->TC_CHANNEL[2].TC_IER=TC_IER_CPCS;
  TC1->TC_CHANNEL[2].TC_IDR=~TC_IER_CPCS;
  NVIC_ClearPendingIRQ(TC5_IRQn);
  NVIC_EnableIRQ(TC5_IRQn);
  TC_Start(TC1, 2);  // Start the counter on DAC1 pin
```
I hope it helps.
Br,
Radek

**Comment by archenemies** [comment]
@radosek21 Thank you for your code! I got it to work but I wanted to make some comments to make it more useful to others:

* Users need to call `pinMode(DAC1, INPUT)` in `setup()`. Otherwise the chip seems to not even function properly (when you have a signal going into DAC1)

* Users need to define a function called `void TC5_Handler()` and it needs to call `TC_GetStatus(TC1, 2)` to clear the interrupt bit

* I was confused by the numbers 1, 2, and 5. This is explained by the tables in previous posts, I guess there are three timer modules, each with 3 channels; channel 2 on module 1 gets interrupt 5 and reads from pin DAC1.

Thanks again. I've been reading and re-reading the datasheet, and didn't get anywhere until I found your example.

**Comment by LolaGa** [comment]
Hello everyone, 
I am trying to make a timer run by an external clock that will come from a generator, but I cannot make it work.
I tried the code before but it does not  work...
i want that the TIOA0 is created by an external clock but I cannot make it work...
i someone can help me 
please
