### ISSUE TITLE
Is it possible to attach external clocks to the timers

### ISSUE THREAD

**Issue by sriranjanr** [ivanseidel/DueTimer#38]
You mention abou external clock but is it possible to attach external clocks to your timer library?Please let me know how.

**Comment by ivanseidel** [comment]
Hello @sriranjanr,
Right now the DueTimer only supports internal clock source, unless you change a few registers that I don't know...
You might see more useful information in the Datasheet.

Best,

**Comment by sriranjanr** [comment]
TC_BMR register is there which needs to be altered to get the External clock input. If you can guide me I will add code to the library.

**Comment by ivanseidel** [comment]
Sorry that I can't help you with this,
If it was a bug or something I could help you more, but this will require a
lot of deep-reading through the Datasheet, and I'm pretty busy right now...

I suggest you to seek someone that already implemented it on the Web, and
you can expand your search by looking for "ARM Cortex M3" instead of
"Arduino DUE".

But if you find the answer, please post here for others.

Best,

--
Ivan Seidel Gomes
http://TendaDigital.net
http://GitHub.com/ivanseidel <http://github.com/ivanseidel>

2015-06-21 12:13 GMT-03:00 sriranjanr <notifications@github.com>:

**Comment by sriranjanr** [comment]
ok

**Comment by ivanseidel** [comment]
I'm sorry that I couldn't help you, my knowledge on this matter was just enough to build this library

Best
